---
- hosts: all
  gather_facts: true
  become: true
  tasks:
#    - name: check if docker is installed
#      debug:
#        msg: "Docker is {{ 'installed' if ansible_docker0.device == 'docker0' else 'not installed' }}"
#        msg: "Docker is {{ 'installed' if ansible_docker0 is defined else 'not installed' }}"
    - name: install zabbix repo on CentOS 8
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
        state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8" and ansible_docker0 is defined
      register: result
    - debug:
        var: result

    - name: install zabbix agent
      yum:
        name: zabbix-agent2.x86_64
        state: present
      when: ansible_distribution == "CentOS"  and ansible_docker0 is defined
      register: result
    - debug:
        var: result
    
    - name: copy zabbix-agent2 config file
      copy:
        src: /etc/ansible/zabbix_agent2.conf
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: 0644
      when: ansible_docker0 is defined
      register: result

    - debug:
        var: result

    - name: add zabbix user to docker group
      user:
        name: 'zabbix'
        groups: 'docker'
        append: yes
      when: ansible_docker0 is defined
      register: result

    - debug:
        var: result

    - name: restart zabbix-agent2 service
      service:
        name: zabbix-agent2
        state: restarted
        enabled: yes
      when: ansible_docker0 is defined
